fullnameOverride: keycloak
image:
  repository: ghcr.io/opentdf/keycloak

command:
  - "/opt/keycloak/bin/kc.sh"
  - "--verbose"
  - "start-dev"

# This next option (enabled) determines whehter or not Keycloak should 
# create a Postgres (uniquely) for Keycloak (true) or not (false).
# 
# Since it's set to fallse, we'll use the Postgres provided by OpenTDF
postgresql:
  enabled: false
externalDatabase:
  host: opentdf-postgresql
  database: keycloak_database

extraEnv: |
  - name: KEYCLOAK_ADMIN
    value: keycloakadmin
  - name: KEYCLOAK_ADMIN_PASSWORD
    value: mykeycloakpassword
  - name: KC_LOG_LEVEL
    value: INFO
  - name: CLAIMS_URL
    value: http://opentdf-entitlement-pdp:3355/entitlements
  - name: KC_DB
    value: postgres
  - name: KC_DB_URL_HOST
    value: opentdf-postgresql
  - name: KC_DB_URL_DATABASE
    value: keycloak_database
  - name: KC_DB_URL_PORT
    value: "5432"
  - name: KC_DB_USERNAME
    value: postgres
  - name: KC_DB_PASSWORD
    value: myPostgresPassword
  - name: KC_HTTP_RELATIVE_PATH
    value: "/auth"
  - name: KC_HOSTNAME_STRICT_HTTPS
    value: "false"
  - name: KC_HOSTNAME_STRICT
    value: "false"
  - name: KC_HTTP_ENABLED
    value: "true"
  - name: KC_HOSTNAME
    value: "localhost:65432"
  - name: KC_HOSTNAME_ADMIN
    value: "localhost:65432"
  - name: KC_PROXY
    value: "edge"
  - name: JAVA_OPTS_APPEND
    value: -Djgroups.dns.query={{ include "keycloak.fullname" . }}-headless
extraEnvFrom: |
  - secretRef:
      name: 'keycloak-secrets'
ingress:
  enabled: true
  ingressClassName: nginx
  rules:
    - host: localhost
      paths: &paths
        - path: /auth(/|$)(.*)
          pathType: Prefix
    - host: host.docker.internal
      paths: *paths
    - host: offline.demo.internal
      paths: *paths
    - host: opentdf.local
      paths: *paths
  tls: null
